# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

# 指定合适触发 CI：每次 push 至 master 分支时触发
on:
  push:
    branches: [master]

env:
  out-dir: vue3-tsx

jobs:
  build:
    name: 构建项目
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: 同步仓库
        uses: actions/checkout@v2

      - name: 安装 Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
      - run: yarn
      - run: yarn run build
      - run: cd ./${{env.out-dir}}
      - name: 提交文件至当前仓库的 gh-pages 分支
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./${{env.out-dir}}
